// ─────────────────────────────────────────────────────────────────────────────
//  scopeSchedulePdf — the Scope / SOW schedule as a landscape Gantt PDF.
//
//  Modelled on Projects_documents/project_schedule_ref.pdf, the MS Project export
//  the business already reads: A4 LANDSCAPE, a task table on the left (ID, indented
//  task name, duration, start, finish) and a time-scaled bar chart on the right,
//  with a legend band and a page number at the foot of every sheet.
//
//  Built with jsPDF from the SAME state the Scope tab renders, so a downloaded
//  schedule can never disagree with what was on screen — nothing here screenshots
//  the DOM. Every bar is drawn as vectors, so it stays crisp at any zoom and a
//  40-row schedule is tens of KB rather than megabytes (the reference itself is a
//  26 MB scan, which is exactly what this avoids).
//
//  WHERE THE NUMBERS COME FROM — nothing is invented:
//    • Start / Finish — resolveTreeSchedule(), the one place this app reconciles a
//      node's dates. A parent IS the span of its children; a leaf takes its own
//      dates, or its period range on its parent's grid. Identical to the on-screen
//      grid and to the Excel export because it is the same function.
//    • Duration — CALENDAR days, inclusive, between those two dates. The reference
//      says "days" meaning MS Project WORKING days, but this system schedules in
//      calendar weeks and months, so a one-week task here is 7 days, not 5.
//      Reporting MS Project's convention over our data would misstate it; the
//      legend says which is meant.
//    • Progress — the weighted roll-up the tab already shows (leaf actual from the
//      weekly cells, parents weighted by weightPct). The leaf reader is handed in
//      by the caller so there is one implementation of it, not two.
//
//  Assets (Poppins + the logo) are fetched from /report-assets at download time,
//  matching analyticsReportPdf.js. Both are optional: the schedule still builds in
//  Helvetica with no logo if either fetch fails.
// ─────────────────────────────────────────────────────────────────────────────
import { jsPDF } from 'jspdf';
import { parseDate, resolveTreeSchedule } from '../../utils/scopeSchedule.js';

// ── Page geometry (A4 landscape, millimetres) ───────────────────────────────
const PW = 297, PH = 210;
const M = 7;
const HEAD_H = 15;          // title band
const COLHEAD_H = 9;        // table + timeline column header
const ROW_H = 4.5;
const LEGEND_H = 11;        // legend band above the footer rule
const RULE_Y = PH - 11;     // green rule; the company line sits under it
// Legend sits clear of the "generated by / page N" line, which sits clear of the
// rule. Deriving all three from RULE_Y keeps that stacking correct if any moves.
const LEGEND_Y = RULE_Y - 4 - LEGEND_H;

// Left table columns — widths in mm, in render order.
const COLS = [
  { k: 'id',    w: 8,  label: 'ID',        align: 'center' },
  { k: 'name',  w: 66, label: 'Task Name', align: 'left'   },
  { k: 'dur',   w: 16, label: 'Duration',  align: 'right'  },
  { k: 'start', w: 17, label: 'Start',     align: 'center' },
  { k: 'end',   w: 17, label: 'Finish',    align: 'center' },
];
const TABLE_W = COLS.reduce((s, c) => s + c.w, 0);
const GX = M + TABLE_W + 2;             // gantt left edge
const GW = PW - M - GX;                 // gantt width

const ASSET_BASE = `${process.env.PUBLIC_URL || ''}/report-assets/`;
const FOOTER_NAME = 'SESOLA POWER PROJECTS PRIVATE LIMITED';

const C = {
  navy:      [0x1F, 0x49, 0x7D],
  rule:      [0xCF, 0xE2, 0xB0],
  ink:       [29, 37, 53],
  body:      [71, 85, 105],
  muted:     [125, 139, 160],
  line:      [222, 228, 238],
  grid:      [232, 236, 243],
  head:      [0xF2, 0xF2, 0xF2],
  zebra:     [250, 251, 253],
  bar:       [93, 173, 226],     // task bar
  barDone:   [21, 101, 163],     // actual-progress fill inside a task bar
  summary:   [61, 74, 94],       // summary bracket
  milestone: [80, 46, 120],
  today:     [214, 69, 65],
};

const DAY_MS = 86400000;
const MON = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];

const d2 = (n) => String(n).padStart(2, '0');
/** dd-mm-yy — compact enough for a 17 mm column and unambiguous here. */
const fmtCell = (d) => (d ? `${d2(d.getDate())}-${d2(d.getMonth() + 1)}-${String(d.getFullYear()).slice(2)}` : '—');
/** d/m — the short marker the reference prints at the ends of summary bars. */
const fmtTick = (d) => (d ? `${d.getMonth() + 1}/${d.getDate()}` : '');

const num = (v) => { const n = Number(v); return Number.isFinite(n) ? n : 0; };
const named = (list) => (list || []).filter(n => (n.name || '').trim());

/** Inclusive calendar days between two dates; 0 when either is missing. */
const durationDays = (a, b) => (a && b ? Math.max(1, Math.round((b - a) / DAY_MS) + 1) : 0);

async function fetchBase64(url) {
  try {
    const res = await fetch(url);
    if (!res.ok) return null;
    const buf = new Uint8Array(await res.arrayBuffer());
    let s = '';
    for (let i = 0; i < buf.length; i += 0x8000) {
      s += String.fromCharCode.apply(null, buf.subarray(i, i + 0x8000));
    }
    return btoa(s);
  } catch { return null; }
}

// ── Task list ───────────────────────────────────────────────────────────────

const mapKids = (nodes, phaseId) => named(nodes).map(n => ({
  id: n.id,
  phaseId,
  nodeId: n.id,
  name: n.name,
  weightPct: n.weightPct,
  startWeek: n.startWeek, endWeek: n.endWeek,
  startDate: n.startDate || '', endDate: n.endDate || '',
  plannedStartDate: n.plannedStartDate, plannedEndDate: n.plannedEndDate, planUnit: n.planUnit,
  children: mapKids(n.children, phaseId),
}));

/**
 * The editor's phase array → one uniform tree, so a depth-1 sub-item and a
 * depth-4 grandchild go through exactly the same code below. Phases key their
 * breakdown as `subItems` and everything under that as `children`; an unsaved row
 * has no id, so one is synthesised (it need only be unique within this render).
 */
const toTree = (phases) => named((phases || []).map((p, i) => ({
  id: p.id != null ? `p${p.id}` : `p_new_${i}`,
  phaseId: p.id,
  nodeId: null,
  name: p.phaseName,
  weightPct: p.weightPct,
  startWeek: p.startWeek, endWeek: p.endWeek,
  startDate: p.startDate || '', endDate: p.endDate || '',
  plannedStartDate: p.plannedStartDate, plannedEndDate: p.plannedEndDate, planUnit: p.planUnit,
  children: mapKids(p.subItems, p.id),
})).map(n => ({ ...n, name: n.name || '' })));

/**
 * Depth-first rows with outline numbers (1, 1.1, 1.1.1 …) and a resolved span.
 *
 * `progressOf(phaseId, nodeId)` returns a LEAF's actual %. A parent is the
 * weight-weighted average of its children — the same rule as rollUpNodes in the
 * Scope tab and ScopeSubItems.rollUp on the server, so all three agree.
 */
export function buildRows(tree, sched, progressOf) {
  const rows = [];
  const walk = (nodes, depth, prefix) => {
    let acc = 0, wsum = 0, plain = 0, n = 0;
    nodes.forEach((node, i) => {
      const outline = prefix ? `${prefix}.${i + 1}` : String(i + 1);
      const s = sched[node.id] || {};
      const start = parseDate(s.startDate), end = parseDate(s.endDate);
      const kids = node.children || [];
      const row = {
        outline, depth, name: node.name,
        start, end,
        days: durationDays(start, end),
        isSummary: kids.length > 0,
        progress: 0,
      };
      rows.push(row);
      row.progress = kids.length
        ? walk(kids, depth + 1, outline)
        : Math.max(0, Math.min(100, num(progressOf(node.phaseId, node.nodeId))));
      // A milestone is a dated point of zero span with no breakdown — the "0 days"
      // rows the reference draws as diamonds (Purchase Order, Payment).
      row.isMilestone = !row.isSummary && !!start && !!end && +start === +end;

      const w = num(node.weightPct);
      plain += row.progress; n += 1;
      if (w > 0) { acc += w * row.progress; wsum += w; }
    });
    if (wsum > 0) return acc / wsum;
    return n ? plain / n : 0;
  };
  walk(tree, 0, '');
  return rows;
}

// ── Time scale ──────────────────────────────────────────────────────────────

const startOfWeek = (d) => {
  const x = new Date(d);
  x.setDate(x.getDate() - ((x.getDay() + 6) % 7));
  x.setHours(0, 0, 0, 0);
  return x;
};
const addDays = (d, n) => { const x = new Date(d); x.setDate(x.getDate() + n); return x; };

/**
 * Header bands for the timeline, picked from how long the project actually runs —
 * the reference's Quarter-over-Month is right for a year and wrong for six weeks.
 * Returns `{ majors, minors }`, each `{ label, start, end }` in real dates.
 */
export function timeScale(t0, t1) {
  const days = (t1 - t0) / DAY_MS;
  const minors = [], majors = [];
  const pushMajor = (label, start, end) => {
    const last = majors[majors.length - 1];
    if (last && last.label === label) last.end = end; else majors.push({ label, start, end });
  };

  if (days <= 120) {                       // up to ~4 months → Month / Week
    for (let w = startOfWeek(t0); w <= t1; w = addDays(w, 7)) {
      const end = addDays(w, 6);
      minors.push({ label: String(w.getDate()), start: new Date(w), end });
      pushMajor(`${MON[w.getMonth()]} ${w.getFullYear()}`, new Date(w), end);
    }
  } else if (days <= 1100) {                // up to ~3 years → Quarter / Month
    const c = new Date(t0.getFullYear(), t0.getMonth(), 1);
    for (let m = c; m <= t1; m = new Date(m.getFullYear(), m.getMonth() + 1, 1)) {
      const end = new Date(m.getFullYear(), m.getMonth() + 1, 0);
      minors.push({ label: MON[m.getMonth()], start: new Date(m), end });
      pushMajor(`Qtr ${Math.floor(m.getMonth() / 3) + 1}, ${m.getFullYear()}`, new Date(m), end);
    }
  } else {                                  // longer → Year / Quarter
    const c = new Date(t0.getFullYear(), Math.floor(t0.getMonth() / 3) * 3, 1);
    for (let q = c; q <= t1; q = new Date(q.getFullYear(), q.getMonth() + 3, 1)) {
      const end = new Date(q.getFullYear(), q.getMonth() + 3, 0);
      minors.push({ label: `Q${Math.floor(q.getMonth() / 3) + 1}`, start: new Date(q), end });
      pushMajor(String(q.getFullYear()), new Date(q), end);
    }
  }
  return { majors, minors };
}

// ── Document ────────────────────────────────────────────────────────────────

/**
 * Build and download the schedule.
 *
 * @param scope      the scope header (plan span + unit, project type, capacity)
 * @param phases     the Scope tab's phase array, breakdowns and all
 * @param header     {projectName, projectId, customer, totalValue}
 * @param progressOf (phaseId, nodeId|null) => that leaf's actual %
 * @param user       who is downloading, for the footer line
 * @param fileName   optional override
 * @returns {rows, pages} so a caller (or a test) can assert what was drawn
 */
export async function exportScopeSchedulePdf({ scope, phases, header = {}, progressOf, user = {}, fileName }) {
  const tree = toTree(phases);
  if (!tree.length) throw new Error('NO_TASKS');

  const projectGrid = (() => {
    const s = scope && scope.plannedStartDate, e = scope && scope.plannedEndDate;
    return s && e
      ? { start: s, end: e, unit: scope.planUnit === 'MONTH' ? 'MONTH' : 'WEEK', count: 1 }
      : null;
  })();
  const sched = resolveTreeSchedule(tree, projectGrid, {});
  const rows = buildRows(tree, sched, progressOf || (() => 0));

  // Timeline window: what the tasks actually span, widened to the plan span so a
  // schedule with one undated branch still sits on the project's own calendar.
  const dates = rows.flatMap(r => [r.start, r.end]).filter(Boolean);
  const planS = parseDate(scope && scope.plannedStartDate);
  const planE = parseDate(scope && scope.plannedEndDate);
  if (planS) dates.push(planS);
  if (planE) dates.push(planE);
  if (!dates.length) throw new Error('NO_DATES');
  let t0 = new Date(Math.min(...dates)), t1 = new Date(Math.max(...dates));
  if (+t1 === +t0) t1 = addDays(t1, 1);          // a single-day plan still needs width
  const { majors, minors } = timeScale(t0, t1);
  // Snap the window to the header bands so the first and last columns are whole.
  t0 = minors[0].start;
  t1 = minors[minors.length - 1].end;

  const doc = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' });
  let family = 'helvetica', logo = null;
  {
    const [reg, bold, png] = await Promise.all([
      fetchBase64(ASSET_BASE + 'Poppins-Regular.ttf'),
      fetchBase64(ASSET_BASE + 'Poppins-Bold.ttf'),
      fetchBase64(ASSET_BASE + 'sesola_logo.png'),
    ]);
    if (reg && bold) {
      doc.addFileToVFS('Poppins-Regular.ttf', reg);
      doc.addFont('Poppins-Regular.ttf', 'Poppins', 'normal');
      doc.addFileToVFS('Poppins-Bold.ttf', bold);
      doc.addFont('Poppins-Bold.ttf', 'Poppins', 'bold');
      family = 'Poppins';
    }
    if (png) logo = 'data:image/png;base64,' + png;
  }
  const font = (style, size, colour) => {
    doc.setFont(family, style);
    doc.setFontSize(size);
    if (colour) doc.setTextColor(...colour);
  };
  const x = (d) => GX + ((d - t0) / (t1 - t0)) * GW;

  const BODY_TOP = M + HEAD_H + COLHEAD_H;
  const BODY_BOT = LEGEND_Y - 3;
  const perPage = Math.max(1, Math.floor((BODY_BOT - BODY_TOP) / ROW_H));
  const pages = Math.ceil(rows.length / perPage);

  // ── chrome, drawn once per page ──
  const drawFrame = () => {
    doc.setFillColor(...C.navy);
    doc.rect(M, M, PW - M * 2, HEAD_H, 'F');
    font('bold', 11, [255, 255, 255]);
    doc.text(header.projectName || (scope && scope.projectType) || 'Project Schedule', M + 3, M + 6);
    font('normal', 7, [226, 235, 246]);
    const bits = [
      header.projectId && `ID: ${header.projectId}`,
      header.customer && `Customer: ${header.customer}`,
      scope && scope.systemCapacity && `Capacity: ${scope.systemCapacity}`,
      (planS || planE) && `Plan: ${fmtCell(planS)} to ${fmtCell(planE)}`,
      header.totalValue && `Value: ${header.totalValue}`,
    ].filter(Boolean).join('   |   ');
    doc.text(bits, M + 3, M + 11.5, { maxWidth: PW - M * 2 - 44 });
    if (logo) {
      try { doc.addImage(logo, 'PNG', PW - M - 36, M + 2.6, 33, 6.5); } catch { /* optional */ }
    }

    // Column header — table side
    const hy = M + HEAD_H;
    doc.setFillColor(...C.head);
    doc.rect(M, hy, TABLE_W, COLHEAD_H, 'F');
    font('bold', 6.8, C.navy);
    let cx = M;
    COLS.forEach(c => {
      const tx = c.align === 'right' ? cx + c.w - 1.5 : c.align === 'center' ? cx + c.w / 2 : cx + 1.5;
      doc.text(c.label, tx, hy + COLHEAD_H - 3, { align: c.align });
      cx += c.w;
    });

    // Column header — timeline: majors over minors, like the reference
    doc.setFillColor(...C.head);
    doc.rect(GX, hy, GW, COLHEAD_H, 'F');
    doc.setDrawColor(...C.line);
    doc.setLineWidth(0.15);
    const midY = hy + COLHEAD_H / 2;
    majors.forEach(mj => {
      const a = Math.max(GX, x(mj.start)), b = Math.min(GX + GW, x(mj.end));
      if (b - a < 1) return;
      doc.line(a, hy, a, midY);
      font('bold', 6.2, C.navy);
      doc.text(mj.label, (a + b) / 2, hy + 3.4, { align: 'center', maxWidth: b - a });
    });
    doc.line(GX, midY, GX + GW, midY);
    minors.forEach(mn => {
      const a = Math.max(GX, x(mn.start)), b = Math.min(GX + GW, x(mn.end));
      if (b - a < 1) return;
      doc.line(a, midY, a, hy + COLHEAD_H);
      if (b - a >= 3.2) {
        font('normal', 5.6, C.body);
        doc.text(mn.label, (a + b) / 2, hy + COLHEAD_H - 2.2, { align: 'center' });
      }
    });
    doc.setDrawColor(...C.line);
    doc.setLineWidth(0.25);
    doc.rect(M, hy, TABLE_W, COLHEAD_H);
    doc.rect(GX, hy, GW, COLHEAD_H);
  };

  const drawLegend = () => {
    const ly = LEGEND_Y;
    doc.setDrawColor(...C.line);
    doc.setLineWidth(0.25);
    doc.rect(M, ly, PW - M * 2, LEGEND_H);
    const items = [
      ['bar', C.bar, 'Task'],
      ['bar', C.barDone, 'Completed portion (actual progress)'],
      ['sum', C.summary, 'Summary / rolled-up branch'],
      ['dia', C.milestone, 'Milestone (0 days)'],
      ['ln', C.today, 'Today'],
    ];
    let lx = M + 4;
    items.forEach(([kind, col, label]) => {
      const cy = ly + 4;
      doc.setFillColor(...col);
      doc.setDrawColor(...col);
      if (kind === 'bar') {
        doc.rect(lx, cy - 0.9, 8, 1.8, 'F');
      } else if (kind === 'sum') {
        doc.rect(lx, cy - 0.8, 8, 1.2, 'F');
        doc.triangle(lx, cy + 0.4, lx + 1.4, cy + 0.4, lx, cy + 1.8, 'F');
        doc.triangle(lx + 8, cy + 0.4, lx + 6.6, cy + 0.4, lx + 8, cy + 1.8, 'F');
      } else if (kind === 'dia') {
        doc.triangle(lx + 4, cy - 1.7, lx + 6, cy, lx + 4, cy + 1.7, 'F');
        doc.triangle(lx + 4, cy - 1.7, lx + 2, cy, lx + 4, cy + 1.7, 'F');
      } else {
        doc.setLineWidth(0.5);
        doc.line(lx + 4, cy - 1.8, lx + 4, cy + 1.8);
      }
      font('normal', 6, C.body);
      doc.text(label, lx + 10, cy + 1);
      lx += 10 + doc.getTextWidth(label) + 8;
    });
    font('normal', 5.4, C.muted);
    doc.text('Duration is calendar days, inclusive. Progress is the weighted roll-up shown on the Scope / SOW tab; '
      + 'a summary row is the span of everything beneath it.', M + 4, ly + LEGEND_H - 2.2);
  };

  // ── rows ──
  for (let p = 0; p < pages; p++) {
    if (p > 0) doc.addPage();
    drawFrame();
    drawLegend();

    const slice = rows.slice(p * perPage, (p + 1) * perPage);
    const top = BODY_TOP;
    const bodyH = slice.length * ROW_H;

    // Timeline gridlines behind the bars, full body height.
    doc.setDrawColor(...C.grid);
    doc.setLineWidth(0.15);
    minors.forEach(mn => {
      const a = x(mn.start);
      if (a > GX && a < GX + GW) doc.line(a, top, a, top + bodyH);
    });

    slice.forEach((r, i) => {
      const y = top + i * ROW_H;
      if (i % 2 === 1) {
        doc.setFillColor(...C.zebra);
        doc.rect(M, y, PW - M * 2, ROW_H, 'F');
      }

      const style = r.isSummary ? 'bold' : 'normal';
      const colour = r.isSummary ? C.ink : C.body;
      let cx = M;
      const cell = (text, col, st, cl) => {
        font(st, 6.1, cl);
        const tx = col.align === 'right' ? cx + col.w - 1.5 : col.align === 'center' ? cx + col.w / 2 : cx + 1.5;
        doc.text(String(text), tx, y + ROW_H - 1.4, { align: col.align, maxWidth: col.w - 3 });
        cx += col.w;
      };

      cell(r.outline, COLS[0], 'normal', C.muted);
      // Indent by depth, the way an outline reads. Truncated rather than wrapped:
      // a wrapped name would push its own bar out of line with its row.
      {
        const col = COLS[1];
        const indent = 1.5 + r.depth * 2.6;
        font(style, 6.1, colour);
        let name = r.name;
        const room = col.w - indent - 2;
        while (name.length > 4 && doc.getTextWidth(name) > room) name = name.slice(0, -2);
        if (name !== r.name) name = name.slice(0, -1) + '…';
        doc.text(name, cx + indent, y + ROW_H - 1.4);
        cx += col.w;
      }
      cell(r.days ? `${r.days} day${r.days === 1 ? '' : 's'}` : '—', COLS[2], style, colour);
      cell(fmtCell(r.start), COLS[3], style, colour);
      cell(fmtCell(r.end), COLS[4], style, colour);

      if (r.start && r.end) {
        const a = Math.max(GX, x(r.start)), b = Math.min(GX + GW, x(r.end));
        const cy = y + ROW_H / 2;
        if (r.isMilestone) {
          doc.setFillColor(...C.milestone);
          doc.triangle(a, cy - 1.5, a + 1.6, cy, a, cy + 1.5, 'F');
          doc.triangle(a, cy - 1.5, a - 1.6, cy, a, cy + 1.5, 'F');
          font('normal', 5.2, C.muted);
          doc.text(fmtTick(r.start), a + 2.4, cy + 1.1);
        } else if (r.isSummary) {
          const w = Math.max(0.8, b - a);
          doc.setFillColor(...C.summary);
          doc.rect(a, cy - 1.5, w, 1.1, 'F');                                  // spine
          doc.triangle(a, cy - 0.4, a + 1.3, cy - 0.4, a, cy + 1.4, 'F');      // end caps
          doc.triangle(a + w, cy - 0.4, a + w - 1.3, cy - 0.4, a + w, cy + 1.4, 'F');
          font('normal', 5.2, C.muted);
          if (a - GX > 6) doc.text(fmtTick(r.start), a - 1, cy + 0.6, { align: 'right' });
          if (GX + GW - (a + w) > 6) doc.text(fmtTick(r.end), a + w + 1, cy + 0.6);
        } else {
          const w = Math.max(0.8, b - a);
          doc.setFillColor(...C.bar);
          doc.rect(a, cy - 1.35, w, 2.7, 'F');
          if (r.progress > 0) {
            doc.setFillColor(...C.barDone);
            doc.rect(a, cy - 1.35, w * Math.min(100, r.progress) / 100, 2.7, 'F');
          }
          if (r.progress > 0 && GX + GW - (a + w) > 8) {
            font('normal', 5.2, C.muted);
            doc.text(`${r.progress.toFixed(0)}%`, a + w + 1, cy + 1);
          }
        }
      }
    });

    // Today marker, over the bars but under the frame.
    const now = new Date();
    now.setHours(0, 0, 0, 0);
    if (now >= t0 && now <= t1) {
      const tx = x(now);
      doc.setDrawColor(...C.today);
      doc.setLineWidth(0.4);
      doc.setLineDashPattern([1, 1], 0);
      doc.line(tx, top, tx, top + bodyH);
      doc.setLineDashPattern([], 0);
    }

    doc.setDrawColor(...C.line);
    doc.setLineWidth(0.25);
    doc.rect(M, top, TABLE_W, bodyH);
    doc.rect(GX, top, GW, bodyH);
  }

  // ── footer, once the page count is settled ──
  const who = user.name || user.userName || 'CRM user';
  const when = new Date().toLocaleString('en-IN');
  const total = doc.getNumberOfPages();
  for (let p = 1; p <= total; p++) {
    doc.setPage(p);
    font('normal', 5.8, C.muted);
    doc.text(`Generated by ${who} on ${when}`, M, RULE_Y - 2);
    doc.text(`Page ${p} of ${total}`, PW - M, RULE_Y - 2, { align: 'right' });
    doc.setDrawColor(...C.rule);
    doc.setLineWidth(0.5);
    doc.line(M, RULE_Y, PW - M, RULE_Y);
    font('bold', 7.5, C.navy);
    doc.text(FOOTER_NAME, PW / 2, RULE_Y + 4.6, { align: 'center' });
  }

  const safe = String(header.projectId || header.projectName || 'project').replace(/[^\w.-]+/g, '_');
  doc.save(fileName || `Project_Schedule_${safe}.pdf`);
  return { rows: rows.length, pages: total };
}

export default exportScopeSchedulePdf;
