// ==========================================
// DUMMY DATA FOR PROJECT COST & EXPENSE MANAGEMENT
// ==========================================

export const dummyExpenses = [
  {
    id: 1,
    expenseDate: '2024-01-15',
    projectId: 'P001',
    projectName: 'Solar Plant - Hyderabad',
    groupName: 'Solar',
    subGroupName: 'Commercial',
    category: 'Travel',
    amount: 15000,
    paymentMode: 'UPI',
    paidBy: 'U001',
    paidByName: 'Rajesh Kumar',
    approvedBy: 'M001',
    approvedByName: 'Priya Sharma',
    status: 'Approved',
    description: 'Site visit to Hyderabad for project inspection and client meeting',
    commissionType: null,
    commissionGivenTo: null,
    commissionPercentage: null,
    commissionFixedAmount: null,
    salesOrderRef: null
  },
  {
    id: 2,
    expenseDate: '2024-01-18',
    projectId: 'P002',
    projectName: 'EPC Project - Mumbai',
    groupName: 'EPC',
    subGroupName: 'Industrial',
    category: 'Site Visit',
    amount: 25000,
    paymentMode: 'Bank Transfer',
    paidBy: 'U002',
    paidByName: 'Amit Patel',
    approvedBy: 'M002',
    approvedByName: 'Suresh Reddy',
    status: 'Approved',
    description: 'Multiple site visits for equipment installation supervision',
    commissionType: null,
    commissionGivenTo: null,
    commissionPercentage: null,
    commissionFixedAmount: null,
    salesOrderRef: null
  },
  {
    id: 3,
    expenseDate: '2024-01-20',
    projectId: 'P001',
    projectName: 'Solar Plant - Hyderabad',
    groupName: 'Solar',
    subGroupName: 'Commercial',
    category: 'Accommodation',
    amount: 8500,
    paymentMode: 'Card',
    paidBy: 'U001',
    paidByName: 'Rajesh Kumar',
    approvedBy: null,
    approvedByName: null,
    status: 'Pending',
    description: 'Hotel stay for 3 nights during project execution phase',
    commissionType: null,
    commissionGivenTo: null,
    commissionPercentage: null,
    commissionFixedAmount: null,
    salesOrderRef: null
  },
  {
    id: 4,
    expenseDate: '2024-01-22',
    projectId: 'P003',
    projectName: 'IoT Implementation - Bangalore',
    groupName: 'IoT',
    subGroupName: 'Smart City',
    category: 'Commission',
    amount: 50000,
    paymentMode: 'Bank Transfer',
    paidBy: 'U003',
    paidByName: 'Vikram Singh',
    approvedBy: 'M001',
    approvedByName: 'Priya Sharma',
    status: 'Approved',
    description: 'Sales commission for securing new IoT contract',
    commissionType: 'Sales',
    commissionGivenTo: 'Ramesh Gupta',
    commissionPercentage: 5,
    commissionFixedAmount: 50000,
    salesOrderRef: 'SO-2024-001'
  },
  {
    id: 5,
    expenseDate: '2024-01-25',
    projectId: 'P002',
    projectName: 'EPC Project - Mumbai',
    groupName: 'EPC',
    subGroupName: 'Industrial',
    category: 'Food',
    amount: 3500,
    paymentMode: 'Cash',
    paidBy: 'U002',
    paidByName: 'Amit Patel',
    approvedBy: null,
    approvedByName: null,
    status: 'Pending',
    description: 'Team lunch and refreshments during site work',
    commissionType: null,
    commissionGivenTo: null,
    commissionPercentage: null,
    commissionFixedAmount: null,
    salesOrderRef: null
  },
  {
    id: 6,
    expenseDate: '2024-01-28',
    projectId: 'P004',
    projectName: 'CCMS Setup - Delhi',
    groupName: 'CCMS',
    subGroupName: 'Government',
    category: 'Miscellaneous',
    amount: 12000,
    paymentMode: 'UPI',
    paidBy: 'U004',
    paidByName: 'Sneha Desai',
    approvedBy: 'M002',
    approvedByName: 'Suresh Reddy',
    status: 'Approved',
    description: 'Office supplies and equipment purchase for project setup',
    commissionType: null,
    commissionGivenTo: null,
    commissionPercentage: null,
    commissionFixedAmount: null,
    salesOrderRef: null
  },
  {
    id: 7,
    expenseDate: '2024-02-01',
    projectId: 'P003',
    projectName: 'IoT Implementation - Bangalore',
    groupName: 'IoT',
    subGroupName: 'Smart City',
    category: 'Travel',
    amount: 18000,
    paymentMode: 'Card',
    paidBy: 'U003',
    paidByName: 'Vikram Singh',
    approvedBy: null,
    approvedByName: null,
    status: 'Rejected',
    description: 'Flight tickets for technical team - exceeded budget limit',
    commissionType: null,
    commissionGivenTo: null,
    commissionPercentage: null,
    commissionFixedAmount: null,
    salesOrderRef: null
  },
  {
    id: 8,
    expenseDate: '2024-02-03',
    projectId: 'P001',
    projectName: 'Solar Plant - Hyderabad',
    groupName: 'Solar',
    subGroupName: 'Commercial',
    category: 'Commission',
    amount: 35000,
    paymentMode: 'Bank Transfer',
    paidBy: 'U001',
    paidByName: 'Rajesh Kumar',
    approvedBy: 'M001',
    approvedByName: 'Priya Sharma',
    status: 'Approved',
    description: 'Referral commission for introducing new client',
    commissionType: 'Referral',
    commissionGivenTo: 'Tech Solutions Pvt Ltd',
    commissionPercentage: 3,
    commissionFixedAmount: 35000,
    salesOrderRef: 'SO-2024-012'
  },
  {
    id: 9,
    expenseDate: '2024-02-05',
    projectId: 'P005',
    projectName: 'Solar Residential - Pune',
    groupName: 'Solar',
    subGroupName: 'Residential',
    category: 'Site Visit',
    amount: 7500,
    paymentMode: 'UPI',
    paidBy: 'U005',
    paidByName: 'Anita Verma',
    approvedBy: 'M003',
    approvedByName: 'Karthik Iyer',
    status: 'Approved',
    description: 'Client site survey and solar panel assessment',
    commissionType: null,
    commissionGivenTo: null,
    commissionPercentage: null,
    commissionFixedAmount: null,
    salesOrderRef: null
  },
  {
    id: 10,
    expenseDate: '2024-02-08',
    projectId: 'P004',
    projectName: 'CCMS Setup - Delhi',
    groupName: 'CCMS',
    subGroupName: 'Government',
    category: 'Accommodation',
    amount: 9800,
    paymentMode: 'Card',
    paidBy: 'U004',
    paidByName: 'Sneha Desai',
    approvedBy: null,
    approvedByName: null,
    status: 'Pending',
    description: 'Hotel accommodation for installation team',
    commissionType: null,
    commissionGivenTo: null,
    commissionPercentage: null,
    commissionFixedAmount: null,
    salesOrderRef: null
  }
];

export const dummyStats = {
  totalExpenses: 184800,
  travelAndSiteVisit: 65500,
  totalCommission: 85000,
  pendingApprovals: 3,
  approvedThisMonth: 152500,
  projectMargin: 450000
};

export const dummyUsers = [
  { id: 'U001', name: 'Rajesh Kumar', role: 'Engineer' },
  { id: 'U002', name: 'Amit Patel', role: 'Engineer' },
  { id: 'U003', name: 'Vikram Singh', role: 'Sales Manager' },
  { id: 'U004', name: 'Sneha Desai', role: 'Project Manager' },
  { id: 'U005', name: 'Anita Verma', role: 'Site Supervisor' }
];

export const dummyManagers = [
  { id: 'M001', name: 'Priya Sharma', role: 'Manager' },
  { id: 'M002', name: 'Suresh Reddy', role: 'Manager' },
  { id: 'M003', name: 'Karthik Iyer', role: 'Admin' }
];

export const dummyProjects = [
  { id: 'P001', name: 'Solar Plant - Hyderabad', location: 'Hyderabad', groupName: 'Solar', subGroupName: 'Commercial' },
  { id: 'P002', name: 'EPC Project - Mumbai', location: 'Mumbai', groupName: 'EPC', subGroupName: 'Industrial' },
  { id: 'P003', name: 'IoT Implementation - Bangalore', location: 'Bangalore', groupName: 'IoT', subGroupName: 'Smart City' },
  { id: 'P004', name: 'CCMS Setup - Delhi', location: 'Delhi', groupName: 'CCMS', subGroupName: 'Government' },
  { id: 'P005', name: 'Solar Residential - Pune', location: 'Pune', groupName: 'Solar', subGroupName: 'Residential' }
];